Update mypy to 1.6.0
The upgrade of mypy from 1.5.1 to 1.6.0 introduces this error:

    src/pykmp/client.py: note: In member "send_request" of class
    "ClientCommunicator":

    src/pykmp/client.py:136:36: error: Incompatible default for argument
    "destination_address" (default has type "int | None", argument has
    type "int")  [assignment]

For more information see https://github.com/python/mypy/issues/16174.

Because it's unclear if this typing complaint can be fixed properly,
this changes the destination address variable into a simple module level
constant for now.